import style from "./main.module.css";

function Main(){
    return (
        <main clssName={style.main}>
          <div>
            <div>
              <section>
                <div>
                  <h2>빅배너</h2>
                  <div>
                    <span>1</span>
                    |
                    <span>5</span>
                  </div>
                  <button>이전배너</button>
                  <button>다음배너</button>
                  <div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                    <div>
                      <div>
                        <picture></picture>
                        <picture></picture>
                      </div>
                    </div>
                  </div>
                  <span></span>
                </div>
              </section>
            </div>
          </div>
        </main>
    )
}

export default Main;